### ISSUE TITLE
Clear store cache on sign-out

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/ember-auth#5]
If two users have access to different data (say, through ownership), a developer may think there is a bug in the backend when the other users' data is displayed. That's because the in-memory data store is not being reset.

Add this somewhere after the sign-out action, probably in a `then()`.

``` js
this.store.unloadAll();
```

Thanks http://emberigniter.com/clear-ember-data-store/

**Comment by gaand** [comment]
@jrhorn424 I believe this is taken care of in the merge from @faetea
