### ISSUE TITLE
Custom error handler for page flow swallows errors

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/ember-auth#9]
```
ember.debug.js:32096 TypeError: Cannot read property 'some' of undefined
    at Class.error (route.js:21)
    at Object.triggerEvent (ember.debug.js:28580)
    at Object.trigger (ember.debug.js:53473)
    at Object.trigger (ember.debug.js:53287)
    at ember.debug.js:53107
    at tryCatch (ember.debug.js:53806)
    at invokeCallback (ember.debug.js:53821)
    at publish (ember.debug.js:53789)
    at publishRejection (ember.debug.js:53724)
    at ember.debug.js:32054
```

Many developers in 012 got this error when starting to work with Ember. Some of them even gave up using Ember because they couldn't Google for help. Why couldn't they Google for help? Because I wrote the code that's causing it: https://github.com/ga-wdi-boston/ember-auth/blob/master/app/application/route.js#L21

So far the solution has to been to comment out the error handler.

In the future, we need to make a decision about how we handle these errors. Do I re-throw? Do I handle more error cases? This will block inclusion of `ember-auth` in `ember-template`.

**Comment by gaand** [comment]
Should 

``` js
this.store.unloadAll();
```

be invoke by a terminal `then` handler?  It looks like this code could run before the sign-out completes.

Could we debug the value of reason to better understand what's going on? i.e.

``` js

let errors = reason.errors;
let unauthorized = errors && errors.some((error) => error.status === '401');
console.log(reason);  // or the ember equivalent.
```

**Comment by jrhorn424** [comment]
> Could we debug the value of reason to better understand what's going on?

@gaand That's a good suggestion.

It occurs to me that we should be handling errors at the individual route handler level, not at the application route. Error handling should be specific to each route, which should allow us to better flash error messages depending on the same status code across different routes.

So, for example, in the sign-in route, an error hook could inspect the status code and suggest: no account (sign up please), invalid username or password, or whatever. The sign-up route error hook could suggest: email already taken, invalid password, or whatever.

> [should clearing the store] be invoke by a terminal then handler? It looks like this code could run before the sign-out completes.

Yes, it should. Possibly a `finally` instead of `then`.

**Comment by gaand** [comment]
`finally` doesn't appear to be Promise/A+ compliant.

**Comment by payne-chris-r** [comment]
Ref: https://github.com/ga-wdi-boston/ember-template/issues/18
